#!/bin/sh
set -e
if [ "$#" -eq 3 ] && [ "$3" == "..data" ]; then
  sha=$(find ${WATCH_DIR} -type f -exec cat {} \; | sha256sum | awk '"'"'{print $1}'"'"')
  kubectl patch deployment ${DEPLOYMENT_NAME} \
    -p "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"uw.systems/${DEPLOYMENT_NAME}\":\"${sha}\"}}}}}"
  kubectl rollout status deployment/${DEPLOYMENT_NAME}
fi
